# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7808bd118c0fe9557283f4ddb38d8d3df391e56c050e7ac7563b3978e678721d23ce312dea2d558d047168a19879441628bf230d9010dd311415ad431010ee80

test:
  secret_key_base: 36e86b3890e56eb455faea00d7807d9a7922cc0c2968ca0e3c0662a9022e33ed35a2d86bbdd9003b6dbe34ce4aa8e5a3bc06e5442fceb661d720cd0dd6d8d413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
